// INFO need an empty line after the POST * line and before the {} for the JSON message
@hostname = {{$processEnv HOST_NJS_INVENTORY }}
@port = {{$processEnv PORT_NJS_INVENTORY }}
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/usertypes/all

###
POST http://{{host}}/usertypes/add HTTP/1.1
content-type: {{contentType}}

{
  "code": "ADIN",
  "desc": " ..."
}

###
GET http://{{host}}/users/all


###
POST http://{{host}}/users/register
content-type: {{contentType}}

{
  "name": "Fari ",
  "email": "whyfari@gmail.com",
  "password": "a",
  "userType_id" : "5d8f6fc6ac2eb713d1b48d0d"
}

###
POST http://{{host}}/users/auth
content-type: {{contentType}}

{
  "email": "whyfari@gmail.com",
  "password": "a"
}